(defproject redirect-fixer "0.1.0-SNAPSHOT"
  :description "connect to drupal db and replace defect urls in node bodies"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [org.clojure/java.jdbc "0.3.6"]
                 [org.clojure/data.csv "0.1.2"]
                 [mysql/mysql-connector-java "5.1.25"]
                 [http-kit "2.1.16"]
                 [enlive "1.1.5"]
                 [intervox/clj-progress "0.1.5"]
                 [com.stuartsierra/component "0.2.2"]
                 [org.clojure/core.async "0.1.346.0-17112a-alpha"]]
  :main ^:skip-aot redirect-fixer.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}
             :test {:dependencies [[http-kit.fake "0.2.1"]
                                   [org.xerial/sqlite-jdbc "3.7.2"]]}}
  :plugins [[lein-auto "0.1.1"]
            [cider/cider-nrepl "0.8.0-SNAPSHOT"]]
  ; exclude tmp files generated by emacs for auto tasks
  :auto {:defaults {:file-pattern #"^(?!\.#).+\.clj$"}})
